trigger:
  branches:
    include:
      - main

stages:
  - stage: macOS_latest
    displayName: 'macOS-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'macOS-latest'
    jobs:
      - job: Nuke
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              version: 6.0.x
          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'tool'
              arguments: 'install --global nuke.globaltool'
          - template: ./azure-pipelines.nuke.yml