trigger:

  branches:
    include:
      - main

stages:
  - stage: macOS_latest
    displayName: 'macOS-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'macOS-latest'
    jobs:
      - job: Nuke
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              version: 6.0.x
          - task: FileTransform@1
            displayName: 'Populate App Settings'
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)'
              fileType: 'json'
              targetFiles: 'src/Versions/appsettings.json'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'custom'
              custom: 'tool'
              arguments: 'install --global nuke.globaltool'
          - template: ./azure-pipelines.nuke.yml
          - task: CopyFiles@2
            displayName: 'Copy Ipa'
            inputs:
              SourceFolder: 'artifacts/ios/'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'
              CleanTargetFolder: true
              OverWrite: true
              preserveTimestamp: true
          - task: CopyFiles@2
            displayName: 'Copy Release Scripts'
            inputs:
              SourceFolder: './.build'
              Contents: '*.sh'
              TargetFolder: '$(build.artifactstagingdirectory)'
              CleanTargetFolder: true
              OverWrite: true
              preserveTimestamp: true

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'