# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do 
  desc "Download the certificates and profiles for the CI"
  lane :ci do |options|    
    match(type: "adhoc", 
          readonly: true,
          force_for_new_devices: true,
          s3_region:ENV['MATCH_S3_REGION'],
          s3_access_key:ENV['MATCH_S3_ACCESS_KEY'],
          s3_secret_access_key:ENV['MATCH_S3_SECRET_ACCESS_KEY'],
          keychain_name: "temporary.keychain", 
          keychain_password: "doesntmatteritwillbetemporaryanyway")
  end
end
